# =================================================================
# Configuration Mosquitto - SmartCampus CI (Groupe D)
# =================================================================

# --- Connexions et Protocoles ---
listener 1883 0.0.0.0
protocol mqtt

# --- Authentification Sécurisée ---
allow_anonymous false
password_file /mosquitto/config/passwd

# --- Persistance des Données (Stockage des messages Retain) ---
persistence true
persistence_location /mosquitto/data/

# --- Traces et Logs (Idéal pour les captures du rapport) ---
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout